// Generated by しくみや — 2026-04-07T07:57:44.359Z
export const siteConfig = {
  name: "Sora",
  siteTitle: "Sora — Comic Gallery",
  description: "漫画とイラストを描いています。AI画像生成を使って、新しい表現を探求中。",
  url: "",
  lang: "ja",
  template: "comic-panel",

  colors: {
    primary: "#00e5ff",
    accent: "#d4a853",
    background: "#0a0a0f",
  },

  hero: {
    tagline: "Gallery",
    catchcopy: "物語は、一コマから始まる",
    motto: "描きたいものを、描きたいように",
    subtitle: "Art Portfolio",
    description: "漫画とイラストを描いています。AI画像生成を使って、新しい表現を探求中。",
    backgroundImage: "/images/hero.webp",
    cta: {
      text: "作品を見る",
      href: "#gallery",
    },
  },

  gallery: {
    title: "GALLERY",
    subtitle: "作品ギャラリー",
    description: "",
    works: [

    ],
    initialDisplay: 8,
  },

  about: {
    title: "ABOUT",
    subtitle: "アーティストについて",
    image: "/images/about.webp",
    paragraphs: ["漫画とイラストを描いています。AI画像生成を使って、新しい表現を探求中。"],
    quote: "描きたいものを、描きたいように",
    genres: [],
    tools: [],
  },

  contact: {
    title: "CONTACT",
    subtitle: "お問い合わせ・SNS",
    description: "お仕事のご依頼・コラボレーション・ご質問はお気軽にどうぞ。",
    email: "ryoya112@outlook.com",
    social: [
    { label: "X (Twitter)", href: "https://x.com/sora_manga_test" },
    { label: "Instagram", href: "https://instagram.com/sora_manga_test" },
    ] as { label: string; href: string }[],
  },

  nav: [
    { label: "Gallery", href: "#gallery" },
    { label: "About", href: "#about" },
    { label: "Contact", href: "#contact" },
  ],

  footer: {
    credit: "Built with Next.js — Template by しくみや",
    copyright: `© ${new Date().getFullYear()} Sora. All rights reserved.`,
  },
};

export type SiteConfig = typeof siteConfig;
